### ISSUE TITLE
LINUX sample execution

### ISSUE THREAD

**Issue by kalai86** [CartoType/CartoType-Public-5-2#2]
HI,

    i run this demo in linux format but i got some error ,i show that error below .pls suggest solution for this.

`MapWindow::MapWindow()':
unix_gl_demo.cpp:(.text+0x171): undefined reference to `CartoType::CString::CString(char const*, unsigned long)'
unix_gl_demo.cpp:(.text+0x18e): undefined reference to `CartoType::CString::CString(char const*, unsigned long)'
unix_gl_demo.cpp:(.text+0x1ab): undefined reference to `CartoType::CString::CString(char const*, unsigned long)'
unix_gl_demo.cpp:(.text+0x1e3): undefined reference to `CartoType::CFramework::New(CartoType::TResult&, CartoType::CString const&, CartoType::CString const&, CartoType::CString const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*)'
unix_gl_demo.o: In function `MapWindow::Draw()':
unix_gl_demo.cpp:(.text+0x4ab): undefined reference to `CartoType::CMapRenderer::Draw()'
unix_gl_demo.o: In function `MapWindow::KeyStroke(int, int, int, int)':
unix_gl_demo.cpp:(.text+0x7e6): undefined reference to `CartoType::CFramework::Zoom(double)'
unix_gl_demo.cpp:(.text+0x816): undefined reference to `CartoType::CFramework::Zoom(double)'
unix_gl_demo.cpp:(.text+0x846): undefined reference to `CartoType::CFramework::Perspective() const'
unix_gl_demo.cpp:(.text+0x856): undefined reference to `CartoType::CFramework::SetPerspective(bool)'
unix_gl_demo.cpp:(.text+0x87d): undefined reference to `CartoType::CFramework::Pan(int, int)'
unix_gl_demo.cpp:(.text+0x8a1): undefined reference to `CartoType::CFramework::Pan(int, int)'
unix_gl_demo.cpp:(.text+0x8c5): undefined reference to `CartoType::CFramework::Pan(int, int)'
unix_gl_demo.cpp:(.text+0x8e9): undefined reference to `CartoType::CFramework::Pan(int, int)'
unix_gl_demo.o: In function `MapWindow::LeftButtonDown(double, double)':
unix_gl_demo.cpp:(.text+0x97c): undefined reference to `CartoType::CFramework::ConvertPoint(double&, double&, CartoType::TCoordType, CartoType::TCoordType) const'
unix_gl_demo.o: In function `MapWindow::RightButtonUp(double, double)':
unix_gl_demo.cpp:(.text+0xa6b): undefined reference to `CartoType::CFramework::ConvertPoint(double&, double&, CartoType::TCoordType, CartoType::TCoordType) const'
unix_gl_demo.o: In function `MapWindow::PanToDraggedPosition()':
unix_gl_demo.cpp:(.text+0xbd5): undefined reference to `CartoType::CFramework::Pan(CartoType::TPoint const&, CartoType::TPoint const&)'
unix_gl_demo.o: In function `MapWindow::MouseMove(double, double)':
unix_gl_demo.cpp:(.text+0xcb2): undefined reference to `CartoType::CFramework::Pan(double, double, CartoType::TCoordType, double, double, CartoType::TCoordType)'
unix_gl_demo.cpp:(.text+0xd59): undefined reference to `CartoType::CFramework::ConvertPoint(double&, double&, CartoType::TCoordType, CartoType::TCoordType) const'
unix_gl_demo.o: In function `MapWindow::MouseWheel(double, double)':
unix_gl_demo.cpp:(.text+0xe8d): undefined reference to `CartoType::CFramework::RotateAt(double, double, double, CartoType::TCoordType)'
unix_gl_demo.cpp:(.text+0xeba): undefined reference to `CartoType::CFramework::Rotate(double)'
unix_gl_demo.cpp:(.text+0xf6d): undefined reference to `CartoType::CFramework::ZoomAt(double, double, double, CartoType::TCoordType)'
unix_gl_demo.cpp:(.text+0xf97): undefined reference to `CartoType::CFramework::Zoom(double)'
unix_gl_demo.o: In function `MapWindow::CalculateAndDisplayRoute()':
unix_gl_demo.cpp:(.text+0x1086): undefined reference to `CartoType::CFramework::StartNavigation(double, double, CartoType::TCoordType, double, double, CartoType::TCoordType)'
unix_gl_demo.o: In function `CartoType::CString::~CString()':
unix_gl_demo.cpp:(.text._ZN9CartoType7CStringD2Ev[_ZN9CartoType7CStringD5Ev]+0xf): undefined reference to `vtable for CartoType::CString'
unix_gl_demo.o: In function `std::_MakeUniq<CartoType::CMapRenderer>::__single_object std::make_unique<CartoType::CMapRenderer, CartoType::CFramework&>(CartoType::CFramework&)':
unix_gl_demo.cpp:(.text._ZSt11make_uniqueIN9CartoType12CMapRendererEJRNS0_10CFrameworkEEENSt9_MakeUniqIT_E15__single_objectEDpOT0_[_ZSt11make_uniqueIN9CartoType12CMapRendererEJRNS0_10CFrameworkEEENSt9_MakeUniqIT_E15__single_objectEDpOT0_]+0x3b): undefined reference to `CartoType::CMapRenderer::CMapRenderer(CartoType::CFramework&, void const*)'
unix_gl_demo.o: In function `std::default_delete<CartoType::CMapRenderer>::operator()(CartoType::CMapRenderer*) const':
unix_gl_demo.cpp:(.text._ZNKSt14default_deleteIN9CartoType12CMapRendererEEclEPS1_[_ZNKSt14default_deleteIN9CartoType12CMapRendererEEclEPS1_]+0x1e): undefined reference to `CartoType::CMapRenderer::~CMapRenderer()'
collect2: error: ld returned 1 exit status

thanks
kalai

**Comment by GrahamAsher** [comment]
Please use the latest version (7.0) from the CartoType-Public repo. It looks as if you are using old source (5.2) with a later version of the CartoType library, or have forgotten to link to the CartoType library. I can no longer support old versions - sorry.

**Comment by kalai86** [comment]
hi,

  linux application not like windows application like map window toolbar and selection process?


thanks
kalai

**Comment by GrahamAsher** [comment]
As mentioned, please use the latest version (7.0) from the CartoType-Public repo, and do write to me directly if you have questions like this.
